version: '3.8'

services:
  whatsapp-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-bot-dev
    restart: "no"
    ports:
      - "8000:8000"
    environment:
      # Development settings
      - PORT=8000
      - PYTHONPATH=/app
    env_file:
      - .env
    volumes:
      # Mount source code for development
      - .:/app:rw
      - /app/__pycache__
      - /app/.venv
    networks:
      - whatsapp-bot-network
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    labels:
      - "com.whatsapp-bot.environment=development"

networks:
  whatsapp-bot-network:
    driver: bridge
