# Generated by Django 5.2.5 on 2025-08-23 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('patient', '0002_remove_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDesire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('want_appointment', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_desires', to='patient.patient')),
            ],
        ),
    ]
