# Generated by Django 5.2.5 on 2025-08-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_patient_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Medical History', 'verbose_name_plural': 'Medical Histories'},
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='notes',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='diagnosis_date',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='medicalhistory',
            name='treatment',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
