# Generated by Django 5.2.5 on 2025-08-23 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_medicalhistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_id',
        ),
    ]
