# Generated by Django 5.2.5 on 2025-08-24 01:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_doctor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hire_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
