# Generated by Django 5.2.5 on 2025-08-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Unique identifier for the chat session', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, help_text='The content of the chat session')),
            ],
            options={
                'verbose_name': 'Chat Data',
                'verbose_name_plural': 'Chat Data',
                'ordering': ['-created_at'],
            },
        ),
    ]
