# Generated by Django 5.2.5 on 2025-08-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatdata',
            old_name='content',
            new_name='initial_questions',
        ),
        migrations.AddField(
            model_name='chatdata',
            name='comments',
            field=models.TextField(blank=True, help_text='Comments from sub-agent analysis', null=True),
        ),
        migrations.AddField(
            model_name='chatdata',
            name='filled_doc',
            field=models.TextField(blank=True, help_text='Complete diagnostic document with detailed analysis', null=True),
        ),
        migrations.AddField(
            model_name='chatdata',
            name='llm_questions',
            field=models.TextField(blank=True, help_text='The content of the chat session'),
        ),
        migrations.AddField(
            model_name='chatdata',
            name='pre_diagnosis',
            field=models.TextField(blank=True, help_text="Pre-diagnostic analysis of the user's condition", null=True),
        ),
        migrations.AddField(
            model_name='chatdata',
            name='score',
            field=models.CharField(blank=True, help_text="Priority score (e.g., 'Alta prioridad', 'Media prioridad')", max_length=50, null=True),
        ),
    ]
