# Generated by Django 5.2.5 on 2025-08-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatdata',
            name='number',
            field=models.CharField(help_text='Unique identifier for the chat session', max_length=30),
        ),
    ]
